export const CREATE_COURSE = "CREATE_COURSE",
  CREATE_COURSES_SUCCESS = "CREATE_COURSES_SUCCESS",
  LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS",
  UPDATE_COURSES_SUCCESS = "UPDATE_COURSES_SUCCESS",
  LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
