export const BEGIN_API_CALL = "BEGIN_API_CALL",
  CREATE_COURSE = "CREATE_COURSE",
  CREATE_COURSES_SUCCESS = "CREATE_COURSES_SUCCESS",
  END_API_CALL = "END_API_CALL",
  LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS",
  UPDATE_COURSES_SUCCESS = "UPDATE_COURSES_SUCCESS",
  LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
